import { blogs } from "@/blogs"

const orderedSlugs = [
  "reinforcement-learning-n-step-sarsa",
  "reinforcement-learning-q-learning",
  "reinforcement-learning-sarsa",
  "reinforcement-learning-off-policy-monte-carlo",
  "reinforcement-learning-model-free-monte-carlo-learner",
  "reinforcement-learning-model-based-adp-learner",
  "reinforcement-learning-value-iteration",
  "reinforcement-learning-policy-iteration",
  "reinforcement-learning-markov-decision-process",
  "reinforcement-learning-multi-armed-bandits",
  "rag-evaluation-part-2-generator-evaluation",
  "rag-evaluation-part-1-retriever-evaluation",
  "evaluation-metrics-for-synthetic-qa-datasets-in-rag-evaluation",
  "rag-enhancing-language-models-with-external-knowledge",
  "annoy-and-efficient-approximate-nearest-neighbor-algorithm",
  "the-react-agent-framework",
  "lora-low-rank-adaptation-for-efficient-fine-tuning",
  "t5-the-text-to-text-transfer-transformer",
  "from-gpt-1-to-gpt-3-a-new-era-in-nlp",
  "a-comprehensive-overview-of-bert",
  "understanding-the-transformer-architecture",
  "self-attention",
  "understanding-scaling-in-self-attention",
  "normalization-in-deep-learning",
  "understanding-padding-and-look-ahead-mask-in-the-transformer-decoder",
  "encoder-decoder-attention-in-the-transformer",
  "sinusoidal-positional-encoding-in-the-transformer",
  "attention-mechanism",
  "encoder-decoder-architecture",
  "model-evaluation-sensitivity-specificity-and-roc-auc",
  "a-lagrange-multiplier-approach-to-pca",
]

export const allBlogs = orderedSlugs.map((slug) => ({
  slug,
  title: blogs[slug].title,
}))
